### PR TITLE
Adding Python Interface Unit Tests

### PR DESCRIPTION
**Pull request by Pedro-Roque**
As in the title. Right now I'm just asserting to True, but should be changed when the interface is running.

### CODE REVIEW

**Comment by darnstrom** [comment]
Thanks for this contribution. Before it can be merged:
I prefer the tests folder to be moved to interfaces/daqp-python/test (note test instead of tests).
I could do the modification myself if you give me permission to push to the fork.

**Comment by Pedro-Roque** [comment]
You should have it now Daniel

**Comment by Pedro-Roque** [comment]
@darnstrom fixed, also fixed the LD_LIBRARY_PATH that was not set correctly. Should be good to merge.

**Review by darnstrom — APPROVED** [review]

**Comment by darnstrom** [comment]
@Pedro-Roque Awesome! Thanks again for the contribution

**Pull request merged**
