### PR TITLE
Set target_include_directories and modify Cmake export

### PR DESCRIPTION
**Pull request by darnstrom**

### CODE REVIEW

**Comment by kkofler** [comment]
Nope, does not work:
```
CMake Error: INSTALL(EXPORT) given unknown export "daqpCmake"
```

**Comment by kkofler** [comment]
The following works for me:
```cmake
install(TARGETS daqpstat EXPORT  ${PROJECT_NAME}Config
  ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
  LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
  RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
install(TARGETS daqp EXPORT  ${PROJECT_NAME}Config
  ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
  LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
  RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
install(FILES ${daqp_headers} ${daqp_codegen_headers} DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/daqp")

install(EXPORT ${PROJECT_NAME}Config DESTINATION cmake)
```
1. It should be `${PROJECT_NAME}Config`, not `${PROJECT_NAME}Cmake`, and
2. the `install` lines also need `${PROJECT_NAME}Config` instead of `${PROJECT_NAME}`.

**Comment by kkofler** [comment]
(The `target_include_directories` part works. It is only the above snippet that needs the 2 aforementioned fixes.)

**Comment by darnstrom** [comment]
> (The `target_include_directories` part works. It is only the above snippet that needs the 2 aforementioned fixes.)

Ok, thank you for the feedback! (the Cmake instead of Config was a typo...) 
Now I think it should work as expected?

**Comment by kkofler** [comment]
Yes, now it works as expected, fixes both #51 and #52, thanks!

**Pull request merged**
